CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE TABLE patients (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        uhid character varying(20) NOT NULL,
        patient_name character varying(100) NOT NULL,
        dob timestamp with time zone NOT NULL,
        gender character varying(10) NOT NULL,
        blood_group character varying(5) NOT NULL,
        mobile character varying(10) NOT NULL,
        email character varying(100) NOT NULL,
        address text NOT NULL,
        postal_code character varying(10) NOT NULL,
        photo text NOT NULL,
        id_proof_type character varying(50) NOT NULL,
        id_proof_number character varying(100) NOT NULL,
        status character varying(20) NOT NULL DEFAULT 'ACTIVE',
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_patients" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE TABLE appointments (
        id text NOT NULL,
        appointment_no text NOT NULL,
        patient_id bigint NOT NULL,
        doctor_id text NOT NULL,
        appointment_date timestamp with time zone NOT NULL,
        start_time interval NOT NULL,
        end_time interval NOT NULL,
        token_number integer NOT NULL,
        status text NOT NULL DEFAULT 'Scheduled',
        visit_type text NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_appointments" PRIMARY KEY (id),
        CONSTRAINT "FK_appointments_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE TABLE attenders (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        patient_id bigint NOT NULL,
        name character varying(100) NOT NULL,
        phone character varying(10) NOT NULL,
        address text NOT NULL,
        id_proof_type character varying(50) NOT NULL,
        id_proof_number character varying(100) NOT NULL,
        CONSTRAINT "PK_attenders" PRIMARY KEY (id),
        CONSTRAINT "FK_attenders_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE TABLE emergency_contacts (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        patient_id bigint NOT NULL,
        name character varying(100) NOT NULL,
        relationship character varying(50) NOT NULL,
        contact_number character varying(10) NOT NULL,
        CONSTRAINT "PK_emergency_contacts" PRIMARY KEY (id),
        CONSTRAINT "FK_emergency_contacts_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE TABLE referrals (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        patient_id bigint NOT NULL,
        data jsonb,
        CONSTRAINT "PK_referrals" PRIMARY KEY (id),
        CONSTRAINT "FK_referrals_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_appointments_appointment_no" ON appointments (appointment_no);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_appointments_doctor_id_appointment_date" ON appointments (doctor_id, appointment_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_appointments_patient_id" ON appointments (patient_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_appointments_status" ON appointments (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_attenders_patient_id" ON attenders (patient_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_emergency_contacts_patient_id" ON emergency_contacts (patient_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_patients_mobile" ON patients (mobile);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_patients_status" ON patients (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_patients_uhid" ON patients (uhid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    CREATE INDEX "IX_referrals_patient_id" ON referrals (patient_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326040216_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260326040216_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326071154_MakePhotoNullable') THEN
    ALTER TABLE patients ALTER COLUMN photo DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326071154_MakePhotoNullable') THEN
    ALTER TABLE patients ALTER COLUMN dob TYPE timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260326071154_MakePhotoNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260326071154_MakePhotoNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    ALTER TABLE appointments ADD "Department" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    ALTER TABLE appointments ADD "Notes" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    ALTER TABLE appointments ADD "Priority" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    CREATE TABLE departments (
        id text NOT NULL,
        name character varying(100) NOT NULL,
        description text,
        created_by character varying(100) NOT NULL,
        updated_by character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_departments" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    CREATE TABLE doctors (
        id text NOT NULL,
        name character varying(100) NOT NULL,
        specialization character varying(100) NOT NULL,
        mobile character varying(10) NOT NULL,
        department_id text NOT NULL,
        created_by character varying(100) NOT NULL,
        updated_by character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_doctors" PRIMARY KEY (id),
        CONSTRAINT "FK_doctors_departments_department_id" FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    CREATE UNIQUE INDEX "IX_departments_name" ON departments (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    CREATE INDEX "IX_doctors_department_id" ON doctors (department_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    CREATE UNIQUE INDEX "IX_doctors_mobile" ON doctors (mobile);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    ALTER TABLE appointments ADD CONSTRAINT "FK_appointments_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063903_departmentanddoctor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327063903_departmentanddoctor', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327063954_departmentanddoctor1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327063954_departmentanddoctor1', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    ALTER TABLE appointments RENAME COLUMN "Priority" TO priority;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    ALTER TABLE appointments RENAME COLUMN "Notes" TO notes;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    ALTER TABLE appointments RENAME COLUMN "Department" TO department;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    ALTER TABLE appointments ALTER COLUMN priority TYPE character varying(20);
    ALTER TABLE appointments ALTER COLUMN priority SET DEFAULT 'normal';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    ALTER TABLE appointments ALTER COLUMN notes SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    ALTER TABLE appointments ALTER COLUMN department TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    CREATE TABLE appointment_reminders (
        id text NOT NULL,
        appointment_id text NOT NULL,
        channel character varying(20) NOT NULL,
        timing character varying(20) NOT NULL,
        CONSTRAINT "PK_appointment_reminders" PRIMARY KEY (id),
        CONSTRAINT "FK_appointment_reminders_appointments_appointment_id" FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    CREATE INDEX "IX_appointment_reminders_appointment_id" ON appointment_reminders (appointment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327073750_appointment_reminders') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327073750_appointment_reminders', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327074751_appointment_date_only') THEN
    ALTER TABLE appointments ALTER COLUMN appointment_date TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327074751_appointment_date_only') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327074751_appointment_date_only', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327110629_appointmentidchanges') THEN
    ALTER TABLE appointments ADD display_id integer GENERATED ALWAYS AS IDENTITY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327110629_appointmentidchanges') THEN
    CREATE UNIQUE INDEX "IX_appointments_display_id" ON appointments (display_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327110629_appointmentidchanges') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327110629_appointmentidchanges', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327120801_AddRevenueRates') THEN
    CREATE TABLE revenue_rates (
        id character varying(50) NOT NULL,
        visit_type character varying(50) NOT NULL,
        rate numeric(12,2) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        is_deleted boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_revenue_rates" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327120801_AddRevenueRates') THEN
    CREATE UNIQUE INDEX "IX_revenue_rates_visit_type" ON revenue_rates (visit_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327120801_AddRevenueRates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327120801_AddRevenueRates', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE TABLE billings (
        id character varying(50) NOT NULL,
        bill_number character varying(50) NOT NULL,
        patient_id bigint NOT NULL,
        appointment_id character varying(50),
        visit_type character varying(50) NOT NULL,
        doctor_id character varying(50) NOT NULL,
        date date NOT NULL,
        subtotal numeric(12,2) NOT NULL,
        discount numeric(12,2) NOT NULL,
        tax numeric(12,2) NOT NULL,
        net_amount numeric(12,2) NOT NULL,
        paid_amount numeric(12,2) NOT NULL,
        payment_mode character varying(20) NOT NULL,
        transaction_id character varying(100),
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        is_deleted boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_billings" PRIMARY KEY (id),
        CONSTRAINT "FK_billings_appointments_appointment_id" FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE SET NULL,
        CONSTRAINT "FK_billings_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_billings_patients_patient_id" FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE TABLE billing_items (
        id character varying(50) NOT NULL,
        billing_id character varying(50) NOT NULL,
        service_name character varying(150) NOT NULL,
        qty integer NOT NULL,
        rate numeric(12,2) NOT NULL,
        amount numeric(12,2) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        is_deleted boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_billing_items" PRIMARY KEY (id),
        CONSTRAINT "FK_billing_items_billings_billing_id" FOREIGN KEY (billing_id) REFERENCES billings (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE INDEX "IX_billing_items_billing_id" ON billing_items (billing_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE INDEX "IX_billings_appointment_id" ON billings (appointment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE UNIQUE INDEX "IX_billings_bill_number" ON billings (bill_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE INDEX "IX_billings_date" ON billings (date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE INDEX "IX_billings_doctor_id" ON billings (doctor_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    CREATE INDEX "IX_billings_patient_id" ON billings (patient_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135054_AddOpdBillingModule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327135054_AddOpdBillingModule', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327135408_opdchanges') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327135408_opdchanges', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260330000000_AddUserManagement') THEN
    CREATE TABLE users (
        id character varying(50) NOT NULL,
        name character varying(100) NOT NULL,
        email character varying(160) NOT NULL,
        password_hash text NOT NULL,
        phone_number character varying(30),
        role integer NOT NULL DEFAULT 9,
        is_active boolean NOT NULL DEFAULT TRUE,
        department_id character varying(50),
        reference_id character varying(50),
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        is_deleted boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260330000000_AddUserManagement') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260330000000_AddUserManagement') THEN
    CREATE INDEX "IX_users_is_active" ON users (is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260330000000_AddUserManagement') THEN
    CREATE INDEX "IX_users_role" ON users (role);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260330000000_AddUserManagement') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260330000000_AddUserManagement', '8.0.0');
    END IF;
END $EF$;
COMMIT;

